### ISSUE TITLE
Submit Button on Footer redirects to localhost

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [ntbol/block-palettes#1]
#### Steps to reproduce 
1. Go to index.php on the site
2. Scroll down to the footer
3. Click submit

#### Current behaviour (bug)
Will be redirected to http://localhost/block-palettes/submit.php

#### Expected behaviour (correct)
Be redirected to https://www.blockpalettes.com//block-palettes/submit.php

Error is in [Line 188](https://github.com/ntbol/block-palettes/blob/4dc8585175939cec30259bd2f0ef6ace629de600/index.php#L188)

**Comment by ntbol** [comment]
Fixed it. Thank you so much for the find :)
